# Generated by Django 4.1.2 on 2022-10-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/csv'),
        ),
    ]
